import { NextResponse } from "next/server"

// Mock data structure based on the screenshots - replace with actual MongoDB connection
const mockIPOData = [
  {
    _id: "1",
    companyName: "Nava AgriTech Ltd",
    logo: "/placeholder.svg?height=60&width=60",
    priceRange: "₹5 - 350",
    openDate: "2024-01-24",
    closeDate: "2024-01-26",
    issueSize: "₹4.8 Cr",
    issueType: "Book Built",
    listingDate: "Not Issued",
    status: "upcoming",
  },
  {
    _id: "2",
    companyName: "EPACK Durable Ltd",
    logo: "/placeholder.svg?height=60&width=60",
    priceRange: "₹5 - 350",
    openDate: "2024-01-24",
    closeDate: "2024-01-26",
    issueSize: "₹4.8 Cr",
    issueType: "Book Built",
    listingDate: "Not Issued",
    status: "upcoming",
  },
  {
    _id: "3",
    companyName: "RK Swamy Ltd",
    logo: "/placeholder.svg?height=60&width=60",
    priceRange: "₹5 - 350",
    openDate: "2024-01-24",
    closeDate: "2024-01-26",
    issueSize: "₹4.8 Cr",
    issueType: "Book Built",
    listingDate: "Not Issued",
    status: "upcoming",
  },
  {
    _id: "4",
    companyName: "Orvell Stays Ltd",
    logo: "/placeholder.svg?height=60&width=60",
    priceRange: "₹5 - 350",
    openDate: "2024-01-24",
    closeDate: "2024-01-26",
    issueSize: "₹4.8 Cr",
    issueType: "Book Built",
    listingDate: "Not Issued",
    status: "upcoming",
  },
  {
    _id: "5",
    companyName: "Imagine marketing Ltd",
    logo: "/placeholder.svg?height=60&width=60",
    priceRange: "₹5 - 350",
    openDate: "2024-01-24",
    closeDate: "2024-01-26",
    issueSize: "₹4.8 Cr",
    issueType: "Book Built",
    listingDate: "Not Issued",
    status: "upcoming",
  },
  {
    _id: "6",
    companyName: "Kala Clinic India Ltd",
    logo: "/placeholder.svg?height=60&width=60",
    priceRange: "₹5 - 350",
    openDate: "2024-01-24",
    closeDate: "2024-01-26",
    issueSize: "₹4.8 Cr",
    issueType: "Book Built",
    listingDate: "Not Issued",
    status: "upcoming",
  },
  {
    _id: "7",
    companyName: "OLA Electric Mobility Ltd",
    logo: "/placeholder.svg?height=60&width=60",
    priceRange: "₹5 - 350",
    openDate: "2024-01-24",
    closeDate: "2024-01-26",
    issueSize: "₹4.8 Cr",
    issueType: "Book Built",
    listingDate: "Not Issued",
    status: "upcoming",
  },
  {
    _id: "8",
    companyName: "One Mobikwik Systems Ltd",
    logo: "/placeholder.svg?height=60&width=60",
    priceRange: "₹5 - 350",
    openDate: "2024-01-24",
    closeDate: "2024-01-26",
    issueSize: "₹4.8 Cr",
    issueType: "Book Built",
    listingDate: "Not Issued",
    status: "upcoming",
  },
  {
    _id: "9",
    companyName: "Le Travenues Technology",
    logo: "/placeholder.svg?height=60&width=60",
    priceRange: "₹5 - 350",
    openDate: "2024-01-24",
    closeDate: "2024-01-26",
    issueSize: "₹4.8 Cr",
    issueType: "Book Built",
    listingDate: "Not Issued",
    status: "upcoming",
  },
  {
    _id: "10",
    companyName: "CMR Green Technologies",
    logo: "/placeholder.svg?height=60&width=60",
    priceRange: "₹5 - 350",
    openDate: "2024-01-24",
    closeDate: "2024-01-26",
    issueSize: "₹4.8 Cr",
    issueType: "Book Built",
    listingDate: "Not Issued",
    status: "upcoming",
  },
  {
    _id: "11",
    companyName: "Wellness Forever",
    logo: "/placeholder.svg?height=60&width=60",
    priceRange: "₹5 - 350",
    openDate: "2024-01-24",
    closeDate: "2024-01-26",
    issueSize: "₹4.8 Cr",
    issueType: "Book Built",
    listingDate: "Not Issued",
    status: "upcoming",
  },
  {
    _id: "12",
    companyName: "PNJ Ventures Ltd",
    logo: "/placeholder.svg?height=60&width=60",
    priceRange: "₹5 - 350",
    openDate: "2024-01-24",
    closeDate: "2024-01-26",
    issueSize: "₹4.8 Cr",
    issueType: "Book Built",
    listingDate: "Not Issued",
    status: "upcoming",
  },
]

export async function GET() {
  try {
    // In a real application, you would connect to MongoDB here
    // const ipos = await db.collection('ipos').find({}).toArray()

    return NextResponse.json({
      success: true,
      data: mockIPOData,
    })
  } catch (error) {
    return NextResponse.json({ success: false, error: "Failed to fetch IPO data" }, { status: 500 })
  }
}
